### ISSUE TITLE
memset and LTO warning

### ISSUE THREAD

**Issue by milipili** [google/re2#202] opened 2019-04-22 03:24 UTC
Hi!

Just to notify an LTO warning (ubuntu 18.04, c++17 mode, release mode, tag `2019-04-01`)

```
<somewhere>/https-github.com-google-re2/re2/regexp.cc: In function ‘Equal’:
lto1: warning: ‘__builtin_memset’: specified size 18446744073709551600 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
```

**Comment by junyer** [comment] 2019-04-22 13:54
Thanks for the report, but it appears that this might be due to one or more bugs in GCC:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86153
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87544

Is it causing actual breakage or does it seem to be "just" a warning?

**Comment by milipili** [comment] 2019-04-23 13:39
It works for now

**Comment by junyer** [comment] 2019-04-23 13:44
If the bug does cause actual breakage, then I will need slightly more details in order to reproduce it and (hopefully) find some way to work around it. If you have already found one, please let me know.

Closing this issue for now.

**Closed by junyer** 2019-04-23 13:44 UTC
