### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [google/re2#165] opened 2018-01-09 22:17 UTC
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by junyer** [comment] 2018-01-11 04:07
Given that you have spammed a number of projects with the same "request", I'm going to close this issue.

**Closed by junyer** 2018-01-11 04:07 UTC

**Comment by mmha** [comment] 2019-04-27 02:19
Hello @junyer,

may I ask you to reconsider? re2 is a popular library that many other projects depend on. More specifically, I'd like to add the SPIR-V tools to Bintray/Conan and re2 is one of its dependencies.

With Conan gaining enough users and attention to not be one of the 1000 other attempts at C++ package managers any longer, it would be good if the upstream developers themselves provide the packaging scripts instead of offloading the packaging process to either the users or a group of volunteers that may or may not do it the way the original developers intended it to be.

**Comment by junyer** [comment] 2019-04-27 05:30
If a user of package manager XYZ desires an RE2 package, they should do the needful themselves because they are already acquainted with the practices and peculiarities of package manager XYZ. That approach also scales with the number of package managers – whereas yours truly does not. ;)

**Comment by mmha** [comment] 2019-04-27 08:38
I'm happy to submit a PR adding the scripts. That's the easy part.

The problem is that *ideally* someone on the maintainer side needs to create a Bintray account such that the CI or the maintainer can push the binary artifacts and the source code which I clearly am not be able to. Which is what this issue was about in the first place (granted, it could have been less spammy and more descriptive of what would need to be done).

**Comment by junyer** [comment] 2019-04-28 06:12
The RE2 project provides source code only and, to my knowledge, that has never prevented anyone from packaging RE2 themselves. If package manager XYZ requires @rsc or me to get involved in an "official" capacity in order to maintain their RE2 packaging, then their model is broken by design.

**Comment by mmha** [comment] 2019-04-28 07:31
It is not required. Most packages are community-written (see also: [Bincrafters](https://github.com/bincrafters/)). But it would make sense to

1. Make the binary artifacts from the CI which have to produces anywys available for reuse
2. Automate this process so updates to the library are immediately pushed and don't require action by 3rd parties
3. Have an example for packagers and distributors on how to package it, what the dependencies are and how to consume it described in testable code, rather than a Markdown file.
4. Do integration testing. All the CMake stuff that has recently been added is completely uncovered by Travis. How can we be sure that `find_package()`ing the package and `target_link_libraries()*` the library works as intended and will continue so in a year or two?

If you disagree or don't want to take any action, then this is fine and I'll write the packaging out of tree. But I think it has benefits for both you as maintainers and us as library users.

**Comment by junyer** [comment] 2019-04-28 15:01
> It is not required. Most packages are community-written (see also: [Bincrafters](https://github.com/bincrafters/)).

I see that https://github.com/bincrafters/conan-abseil/ and https://github.com/bincrafters/conan-gtest/ exist already, so creating https://github.com/bincrafters/conan-re2/ seems reasonable. Please feel free to loop me in on any issues where I might be able to help.
