### ISSUE TITLE
Can't install pyre2 on a CPanel Linux Server

### ISSUE THREAD

**Issue by vionemc** [google/re2#133] opened 2017-02-19 23:35 UTC
When I try to install it, I got this error:

```
Installing collected packages: re2
  Running setup.py install for re2 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fYerjr/re2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_gvbK2-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 're2' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/re2.cpp -o build/temp.linux-x86_64-2.7/src/re2.o
    src/re2.cpp:249:29: fatal error: re2/stringpiece.h: No such file or directory
     #include "re2/stringpiece.h"
                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fYerjr/re2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_gvbK2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fYerjr/re2/
```

**Comment by junyer** [comment] 2017-02-20 02:20
Closing this as a duplicate of https://github.com/google/re2/issues/116:

> Sorry, I'm unable to help with the Python package, but I believe that it's for the Python wrapper from https://github.com/axiak/pyre2, so filing a bug there instead seems like the right way to go. :)

**Closed by junyer** 2017-02-20 02:20 UTC
